#Stack using list
stack=list((25,20,10,5))
print('stack:',stack)
stack.pop()
print('stack_pop:',stack)
stack.pop()
print('stack_pop:',stack)
stack.append(15)
print('stack_append(15):',stack)
stack.append(20)
print('stack_append(20):',stack)
stack.append(25)
print('stack_append(25):',stack)
stack.clear()
print('stack_clear():',stack)
stack.append(50)
print('stack_append(50):',stack)